# Generated by Django 5.0.6 on 2026-08-08 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0004_house_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='house',
            options={'ordering': ['-active', 'name'], 'verbose_name': 'дом', 'verbose_name_plural': 'дома'},
        ),
    ]
